### ISSUE TITLE
환경변수 처리하기

### ISSUE THREAD

**Issue by Joohyun9219** [Joohyun9219/42_Shell-with-me-minishell#10]

**Comment by Joohyun9219** [comment]
![image](https://user-images.githubusercontent.com/68218329/172013816-c3408d97-9fa1-4d3e-b9f2-b5efd85ef5a9.png)

![image](https://user-images.githubusercontent.com/68218329/172013846-1efe7ce1-5779-44fe-a76f-21813eb9da04.png)

![image](https://user-images.githubusercontent.com/68218329/172013859-d69c35b8-fd52-46e3-8566-5831a52decc5.png)

**Comment by Joohyun9219** [comment]
https://stackoverflow.com/questions/34300527/how-do-i-program-my-own-setenv

https://stackoverflow.com/questions/38197264/using-global-variable-char-environ-to-implement-setenv-and-unsetenv

**Comment by Joohyun9219** [comment]
- 최초의 envron 변수 free 가능한 지 파악
- envron 변수 복사해서 힙에 가지고 처리하는게 올바른 방법
- 파일이 아닌게 프로세스별로 가지고 있어야해서 프로세스는 영원히 지속되지 않으니 메모리에 있는게 맞다

**Comment by kanghyki** [comment]
> * 최초의 envron 변수 free 가능한 지 파악

- 최초의 environment 변수는 초기화 할 수 없음

**Comment by kanghyki** [comment]
<KEY>=<VALUE> 추출

**Comment by kanghyki** [comment]
key=value
