### ISSUE TITLE
코드 리뷰와 수정사항

### ISSUE THREAD

**Issue by Joohyun9219** [Joohyun9219/42_Shell-with-me-minishell#16]
# 코드 리뷰와 수정사항

### jokang
- 인자 없는 리다이렉션 처리 ex) << a, < a, > a, >> a
- 멀티 파이프 시 마지막에 읽어올 파이프 로직 추가
- echo 처리
<img width="523" alt="image" src="https://user-images.githubusercontent.com/68218329/173566814-112f1b05-29f4-4fe8-900e-e21ebbd4d3f1.png">

---
### kanghyki
- ~ 파싱
- 스탠다드 매크로 일단 쓰다가 나중에 norm 맞출 때 수정하기
---
### Common
- $?로 파싱, 그리고 연결해줄 전역 변수
- 프로세스 종료시 $?에 배쉬 에러코드에 맞게 구현

**Comment by Joohyun9219** [comment]
## 구현

- exit함수 구현하기
- 인자 없는 리다이렉션 처리 ex) << a, < a, > a, >> a
- 멀티 파이프 시 마지막에 읽어올 파이프 로직 추가
- echo 처리

![Untitled](https://s3-us-west-2.amazonaws.com/secure.notion-static.com/cb8934c7-fd89-4079-be68-a5869087f275/Untitled.png)

코드 리펙토링과 bash 쉘가 결과가 같게 나오게 코드 수정

### **Common**

- $?로 파싱, 그리고 연결해줄 전역 변수
- 프로세스 종료시 $?에 배쉬 에러코드에 맞게 구현
- 시그널 부분 점검

**Comment by kanghyki** [comment]
## 환경변수

- 기존 **더블 포인터**로 제어하던 환경 변수를 **이진 트리**로 수정할 필요성이 있음
<img width="114" alt="Screen Shot 2022-06-15 at 17 50 47" src="https://user-images.githubusercontent.com/94736461/173785651-8a6e8735-86f0-4441-b132-f18642af461d.png">
<img width="153" alt="Screen Shot 2022-06-15 at 17 51 04" src="https://user-images.githubusercontent.com/94736461/173785660-f8719540-1a3d-4b3d-aef6-604b856d3cfb.png">

1. env와 export가 출력하는 형식이 다름
2. export 커맨드 사용 시 출력이 정렬 되어 나옴
