### ISSUE TITLE
프롬프트 입출력

### ISSUE THREAD

**Issue by Joohyun9219** [Joohyun9219/42_Shell-with-me-minishell#3]

**Comment by Joohyun9219** [comment]
미니쉘 프폼프트 구현은 readline 관련 레퍼런스입니다
https://velog.io/@sham/minishell%EA%B3%BC-readline

**Comment by kanghyki** [comment]
1. 입력 받은 커멘드는 메인에서 관리
2. builtin 명령어와 외부 명령어 분리

**Comment by kanghyki** [comment]
# brew install
https://github.com/gcamerli/42brew

**Comment by kanghyki** [comment]
### readline
<img width="665" alt="Screen Shot 2022-06-09 at 4 44 59" src="https://user-images.githubusercontent.com/94736461/172703928-35f0bf34-c9c4-4f03-a6df-ed72f8f85960.png">
파이프로 끝나는 문자열에서 readline 함수를 탈출하지 못하는 현상 발견 (파이프에서 문자열이 끝나야 함)
